version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - TZ=America/New_York
    volumes:
      - ./data:/usr/src/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    user: "1000:1000" 